//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSubjectTable
    {
        public int ClassSubjectID { get; set; }
        public int SubjectID { get; set; }
        public int ClassID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ClassTable ClassTable { get; set; }
        public virtual SubjectTable SubjectTable { get; set; }
    }
}
