//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.AttendanceTables = new HashSet<AttendanceTable>();
            this.ExamMarksTables = new HashSet<ExamMarksTable>();
            this.SubmissionFeeTables = new HashSet<SubmissionFeeTable>();
            this.StudentPromoteTables = new HashSet<StudentPromoteTable>();
        }
    
        public int StudentID { get; set; }
        public int UserID { get; set; }
        public int SessionID { get; set; }
        public int ProgramID { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public System.DateTime DateofBirth { get; set; }
        public string Gender { get; set; }
        public string ContactNo { get; set; }
        public string CNIC { get; set; }
        public string FNIC { get; set; }
        public string Photo { get; set; }
        public bool IsEnrolled { get; set; }
        public bool IsShortlist { get; set; }
        public bool IsApply { get; set; }
        public System.DateTime ApplyDate { get; set; }
        public string PreviousSchool { get; set; }
        public double PreviousPercentage { get; set; }
        public string EmailAddress { get; set; }
        public string Address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceTable> AttendanceTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamMarksTable> ExamMarksTables { get; set; }
        public virtual ProgramTable ProgramTable { get; set; }
        public virtual SessionTable SessionTable { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionFeeTable> SubmissionFeeTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentPromoteTable> StudentPromoteTables { get; set; }
    }
}
